# Generated by Django 5.0 on 2023-12-15 04:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Shopping.admin'),
            preserve_default=False,
        ),
    ]
